SET NAMES utf8;

TRUNCATE suey_profiling_choices;

INSERT INTO suey_profiling_choices (url) VALUES
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/americanapparel%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/apple%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/bananarepublic%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/bottegaveneta%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/boudinsourdough%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/bristolfarms%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/champs%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/chilis%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/cinnabon%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/claires%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/cpk%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/gamestop%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/GAP%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/gucci%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/guess%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/h%26m%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/hallmark%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/hermes%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/jeanswarehouse%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/lacoste%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/longs%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/lv%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/macys%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/microsoft%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/nobu%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/pandas%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/philz%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/ralphlauren%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/safeway%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/sanrio%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/sears%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/seescandies%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/shakeys%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/starbucks%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/t%26c%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/tealeaf%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/thecheesecakefactory%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/wholefoods%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/xxiforever%402x.png'),
('https://s3-us-west-1.amazonaws.com/ss-brands-logos/zales%402x.png');
