<?php

return array(
    'active_countries' => array('AR', 'US', 'SG'),
    'default_timezone' => 'America/Los_Angeles',
    'list' => array(
        array('iso' => 'AF','country' => 'Afghanistan','name' => 'Kabul','gmt_offset' => '4.5','dst_offset' => '4.5','tz' => 'Asia/Kabul'),
        array('iso' => 'AL','country' => 'Albania','name' => 'Tirane','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Tirane'),
        array('iso' => 'DZ','country' => 'Algeria','name' => 'Algiers','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Algiers'),
        array('iso' => 'AS','country' => 'American Samoa','name' => 'Pago Pago','gmt_offset' => '-11.0','dst_offset' => '-11.0','tz' => 'Pacific/Pago_Pago'),
        array('iso' => 'AD','country' => 'Andorra','name' => 'Andorra','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Andorra'),
        array('iso' => 'AO','country' => 'Angola','name' => 'Luanda','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Luanda'),
        array('iso' => 'AI','country' => 'Anguilla','name' => 'Anguilla','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Anguilla'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Casey','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Antarctica/Casey'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Davis','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Antarctica/Davis'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'DumontDUrville','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Antarctica/DumontDUrville'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Macquarie','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Antarctica/Macquarie'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Mawson','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Antarctica/Mawson'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'McMurdo','gmt_offset' => '13.0','dst_offset' => '12.0','tz' => 'Antarctica/McMurdo'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Palmer','gmt_offset' => '-3.0','dst_offset' => '-4.0','tz' => 'Antarctica/Palmer'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Rothera','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'Antarctica/Rothera'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'South Pole','gmt_offset' => '13.0','dst_offset' => '12.0','tz' => 'Antarctica/South_Pole'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Syowa','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Antarctica/Syowa'),
        array('iso' => 'AQ','country' => 'Antarctica','name' => 'Vostok','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Antarctica/Vostok'),
        array('iso' => 'AG','country' => 'Antigua and Barbuda','name' => 'Antigua','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Antigua'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Buenos Aires','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Buenos_Aires'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Catamarca','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Catamarca'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Cordoba','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Cordoba'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Jujuy','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Jujuy'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'La Rioja','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/La_Rioja'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Mendoza','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Mendoza'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Rio Gallegos','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Rio_Gallegos'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Salta','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Salta'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'San Juan','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/San_Juan'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'San Luis','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/San_Luis'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Tucuman','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Tucuman'),
        array('iso' => 'AR','country' => 'Argentina','name' => 'Ushuaia','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Argentina/Ushuaia'),
        array('iso' => 'AM','country' => 'Armenia','name' => 'Yerevan','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Asia/Yerevan'),
        array('iso' => 'AW','country' => 'Aruba','name' => 'Aruba','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Aruba'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Adelaide','gmt_offset' => '10.5','dst_offset' => '9.5','tz' => 'Australia/Adelaide'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Brisbane','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Australia/Brisbane'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Broken Hill','gmt_offset' => '10.5','dst_offset' => '9.5','tz' => 'Australia/Broken_Hill'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Currie','gmt_offset' => '11.0','dst_offset' => '10.0','tz' => 'Australia/Currie'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Darwin','gmt_offset' => '9.5','dst_offset' => '9.5','tz' => 'Australia/Darwin'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Eucla','gmt_offset' => '8.8','dst_offset' => '8.8','tz' => 'Australia/Eucla'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Hobart','gmt_offset' => '11.0','dst_offset' => '10.0','tz' => 'Australia/Hobart'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Lindeman','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Australia/Lindeman'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Lord Howe','gmt_offset' => '11.0','dst_offset' => '10.5','tz' => 'Australia/Lord_Howe'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Melbourne','gmt_offset' => '11.0','dst_offset' => '10.0','tz' => 'Australia/Melbourne'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Perth','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Australia/Perth'),
        array('iso' => 'AU','country' => 'Australia','name' => 'Sydney','gmt_offset' => '11.0','dst_offset' => '10.0','tz' => 'Australia/Sydney'),
        array('iso' => 'AT','country' => 'Austria','name' => 'Vienna','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Vienna'),
        array('iso' => 'AZ','country' => 'Azerbaijan','name' => 'Baku','gmt_offset' => '4.0','dst_offset' => '5.0','tz' => 'Asia/Baku'),
        array('iso' => 'BS','country' => 'Bahamas','name' => 'Nassau','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Nassau'),
        array('iso' => 'BH','country' => 'Bahrain','name' => 'Bahrain','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Bahrain'),
        array('iso' => 'BD','country' => 'Bangladesh','name' => 'Dhaka','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Dhaka'),
        array('iso' => 'BB','country' => 'Barbados','name' => 'Barbados','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Barbados'),
        array('iso' => 'BY','country' => 'Belarus','name' => 'Minsk','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Europe/Minsk'),
        array('iso' => 'BE','country' => 'Belgium','name' => 'Brussels','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Brussels'),
        array('iso' => 'BZ','country' => 'Belize','name' => 'Belize','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Belize'),
        array('iso' => 'BJ','country' => 'Benin','name' => 'Porto-Novo','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Porto-Novo'),
        array('iso' => 'BM','country' => 'Bermuda','name' => 'Bermuda','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'Atlantic/Bermuda'),
        array('iso' => 'BT','country' => 'Bhutan','name' => 'Thimphu','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Thimphu'),
        array('iso' => 'BO','country' => 'Bolivia','name' => 'La Paz','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/La_Paz'),
        array('iso' => 'BA','country' => 'Bosnia and Herzegovina','name' => 'Sarajevo','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Sarajevo'),
        array('iso' => 'BW','country' => 'Botswana','name' => 'Gaborone','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Gaborone'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Araguaina','gmt_offset' => '-2.0','dst_offset' => '-3.0','tz' => 'America/Araguaina'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Bahia','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Bahia'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Belem','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Belem'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Boa Vista','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Boa_Vista'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Campo Grande','gmt_offset' => '-3.0','dst_offset' => '-4.0','tz' => 'America/Campo_Grande'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Cuiaba','gmt_offset' => '-3.0','dst_offset' => '-4.0','tz' => 'America/Cuiaba'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Eirunepe','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Eirunepe'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Fortaleza','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Fortaleza'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Maceio','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Maceio'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Manaus','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Manaus'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Noronha','gmt_offset' => '-2.0','dst_offset' => '-2.0','tz' => 'America/Noronha'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Porto Velho','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Porto_Velho'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Recife','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Recife'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Rio Branco','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Rio_Branco'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Santarem','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Santarem'),
        array('iso' => 'BR','country' => 'Brazil','name' => 'Sao Paulo','gmt_offset' => '-2.0','dst_offset' => '-3.0','tz' => 'America/Sao_Paulo'),
        array('iso' => 'IO','country' => 'British Indian Ocean Territory','name' => 'Chagos','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Indian/Chagos'),
        array('iso' => 'BN','country' => 'Brunei Darussalam','name' => 'Brunei','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Brunei'),
        array('iso' => 'BG','country' => 'Bulgaria','name' => 'Sofia','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Sofia'),
        array('iso' => 'BF','country' => 'Burkina Faso','name' => 'Ouagadougou','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Ouagadougou'),
        array('iso' => 'BI','country' => 'Burundi','name' => 'Bujumbura','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Bujumbura'),
        array('iso' => 'KH','country' => 'Cambodia','name' => 'Phnom Penh','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Phnom_Penh'),
        array('iso' => 'CM','country' => 'Cameroon','name' => 'Douala','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Douala'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Atikokan','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Atikokan'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Blanc-Sablon','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Blanc-Sablon'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Cambridge Bay','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Cambridge_Bay'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Creston','gmt_offset' => '-7.0','dst_offset' => '-7.0','tz' => 'America/Creston'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Dawson','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Dawson'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Dawson Creek','gmt_offset' => '-7.0','dst_offset' => '-7.0','tz' => 'America/Dawson_Creek'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Edmonton','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Edmonton'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Glace Bay','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'America/Glace_Bay'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Goose Bay','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'America/Goose_Bay'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Halifax','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'America/Halifax'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Inuvik','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Inuvik'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Iqaluit','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Iqaluit'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Moncton','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'America/Moncton'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Montreal','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Montreal'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Nipigon','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Nipigon'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Pangnirtung','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Pangnirtung'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Rainy River','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Rainy_River'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Rankin Inlet','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Rankin_Inlet'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Regina','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Regina'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Resolute','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Resolute'),
        array('iso' => 'CA','country' => 'Canada','name' => 'St Johns','gmt_offset' => '-3.5','dst_offset' => '-2.5','tz' => 'America/St_Johns'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Swift Current','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Swift_Current'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Thunder Bay','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Thunder_Bay'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Toronto','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Toronto'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Vancouver','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Vancouver'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Whitehorse','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Whitehorse'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Winnipeg','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Winnipeg'),
        array('iso' => 'CA','country' => 'Canada','name' => 'Yellowknife','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Yellowknife'),
        array('iso' => 'CV','country' => 'Cape Verde','name' => 'Cape Verde','gmt_offset' => '-1.0','dst_offset' => '-1.0','tz' => 'Atlantic/Cape_Verde'),
        array('iso' => 'KY','country' => 'Cayman Islands','name' => 'Cayman','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Cayman'),
        array('iso' => 'CF','country' => 'Central African Republic','name' => 'Bangui','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Bangui'),
        array('iso' => 'TD','country' => 'Chad','name' => 'Ndjamena','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Ndjamena'),
        array('iso' => 'CL','country' => 'Chile','name' => 'Santiago','gmt_offset' => '-3.0','dst_offset' => '-4.0','tz' => 'America/Santiago'),
        array('iso' => 'CL','country' => 'Chile','name' => 'Easter','gmt_offset' => '-5.0','dst_offset' => '-6.0','tz' => 'Pacific/Easter'),
        array('iso' => 'CN','country' => 'China','name' => 'Chongqing','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Chongqing'),
        array('iso' => 'CN','country' => 'China','name' => 'Harbin','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Harbin'),
        array('iso' => 'CN','country' => 'China','name' => 'Kashgar','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Kashgar'),
        array('iso' => 'CN','country' => 'China','name' => 'Shanghai','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Shanghai'),
        array('iso' => 'CN','country' => 'China','name' => 'Urumqi','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Urumqi'),
        array('iso' => 'CX','country' => 'Christmas Island','name' => 'Christmas','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Indian/Christmas'),
        array('iso' => 'CC','country' => 'Cocos (Keeling) Islands','name' => 'Cocos','gmt_offset' => '6.5','dst_offset' => '6.5','tz' => 'Indian/Cocos'),
        array('iso' => 'CO','country' => 'Colombia','name' => 'Bogota','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Bogota'),
        array('iso' => 'KM','country' => 'Comoros','name' => 'Comoro','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Indian/Comoro'),
        array('iso' => 'CG','country' => 'Congo','name' => 'Brazzaville','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Brazzaville'),
        array('iso' => 'CD','country' => 'Congo, the Democratic Republic of the','name' => 'Kinshasa','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Kinshasa'),
        array('iso' => 'CD','country' => 'Congo, the Democratic Republic of the','name' => 'Lubumbashi','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Lubumbashi'),
        array('iso' => 'CK','country' => 'Cook Islands','name' => 'Rarotonga','gmt_offset' => '-10.0','dst_offset' => '-10.0','tz' => 'Pacific/Rarotonga'),
        array('iso' => 'CR','country' => 'Costa Rica','name' => 'Costa Rica','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Costa_Rica'),
        array('iso' => 'CI','country' => 'Cote D\'Ivoire','name' => 'Abidjan','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Abidjan'),
        array('iso' => 'HR','country' => 'Croatia','name' => 'Zagreb','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Zagreb'),
        array('iso' => 'CU','country' => 'Cuba','name' => 'Havana','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Havana'),
        array('iso' => 'CY','country' => 'Cyprus','name' => 'Nicosia','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Asia/Nicosia'),
        array('iso' => 'CZ','country' => 'Czech Republic','name' => 'Prague','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Prague'),
        array('iso' => 'DK','country' => 'Denmark','name' => 'Copenhagen','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Copenhagen'),
        array('iso' => 'DJ','country' => 'Djibouti','name' => 'Djibouti','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Djibouti'),
        array('iso' => 'DM','country' => 'Dominica','name' => 'Dominica','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Dominica'),
        array('iso' => 'DO','country' => 'Dominican Republic','name' => 'Santo Domingo','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Santo_Domingo'),
        array('iso' => 'EC','country' => 'Ecuador','name' => 'Guayaquil','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Guayaquil'),
        array('iso' => 'EC','country' => 'Ecuador','name' => 'Galapagos','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'Pacific/Galapagos'),
        array('iso' => 'EG','country' => 'Egypt','name' => 'Cairo','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Cairo'),
        array('iso' => 'SV','country' => 'El Salvador','name' => 'El Salvador','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/El_Salvador'),
        array('iso' => 'GQ','country' => 'Equatorial Guinea','name' => 'Malabo','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Malabo'),
        array('iso' => 'ER','country' => 'Eritrea','name' => 'Asmara','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Asmara'),
        array('iso' => 'EE','country' => 'Estonia','name' => 'Tallinn','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Tallinn'),
        array('iso' => 'ET','country' => 'Ethiopia','name' => 'Addis Ababa','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Addis_Ababa'),
        array('iso' => 'FK','country' => 'Falkland Islands (Malvinas)','name' => 'Stanley','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'Atlantic/Stanley'),
        array('iso' => 'FO','country' => 'Faroe Islands','name' => 'Faroe','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Atlantic/Faroe'),
        array('iso' => 'FJ','country' => 'Fiji','name' => 'Fiji','gmt_offset' => '13.0','dst_offset' => '12.0','tz' => 'Pacific/Fiji'),
        array('iso' => 'FI','country' => 'Finland','name' => 'Helsinki','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Helsinki'),
        array('iso' => 'FR','country' => 'France','name' => 'Paris','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Paris'),
        array('iso' => 'GF','country' => 'French Guiana','name' => 'Cayenne','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Cayenne'),
        array('iso' => 'PF','country' => 'French Polynesia','name' => 'Gambier','gmt_offset' => '-9.0','dst_offset' => '-9.0','tz' => 'Pacific/Gambier'),
        array('iso' => 'PF','country' => 'French Polynesia','name' => 'Marquesas','gmt_offset' => '-9.5','dst_offset' => '-9.5','tz' => 'Pacific/Marquesas'),
        array('iso' => 'PF','country' => 'French Polynesia','name' => 'Tahiti','gmt_offset' => '-10.0','dst_offset' => '-10.0','tz' => 'Pacific/Tahiti'),
        array('iso' => 'TF','country' => 'French Southern Territories','name' => 'Kerguelen','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Indian/Kerguelen'),
        array('iso' => 'GA','country' => 'Gabon','name' => 'Libreville','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Libreville'),
        array('iso' => 'GM','country' => 'Gambia','name' => 'Banjul','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Banjul'),
        array('iso' => 'GE','country' => 'Georgia','name' => 'Tbilisi','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Asia/Tbilisi'),
        array('iso' => 'DE','country' => 'Germany','name' => 'Berlin','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Berlin'),
        array('iso' => 'GH','country' => 'Ghana','name' => 'Accra','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Accra'),
        array('iso' => 'GI','country' => 'Gibraltar','name' => 'Gibraltar','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Gibraltar'),
        array('iso' => 'GR','country' => 'Greece','name' => 'Athens','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Athens'),
        array('iso' => 'GL','country' => 'Greenland','name' => 'Danmarkshavn','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'America/Danmarkshavn'),
        array('iso' => 'GL','country' => 'Greenland','name' => 'Godthab','gmt_offset' => '-3.0','dst_offset' => '-2.0','tz' => 'America/Godthab'),
        array('iso' => 'GL','country' => 'Greenland','name' => 'Scoresbysund','gmt_offset' => '-1.0','dst_offset' => '0.0','tz' => 'America/Scoresbysund'),
        array('iso' => 'GL','country' => 'Greenland','name' => 'Thule','gmt_offset' => '-4.0','dst_offset' => '-3.0','tz' => 'America/Thule'),
        array('iso' => 'GD','country' => 'Grenada','name' => 'Grenada','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Grenada'),
        array('iso' => 'GP','country' => 'Guadeloupe','name' => 'Guadeloupe','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Guadeloupe'),
        array('iso' => 'GU','country' => 'Guam','name' => 'Guam','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Pacific/Guam'),
        array('iso' => 'GT','country' => 'Guatemala','name' => 'Guatemala','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Guatemala'),
        array('iso' => 'GN','country' => 'Guinea','name' => 'Conakry','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Conakry'),
        array('iso' => 'GW','country' => 'Guinea-Bissau','name' => 'Bissau','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Bissau'),
        array('iso' => 'GY','country' => 'Guyana','name' => 'Guyana','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Guyana'),
        array('iso' => 'HT','country' => 'Haiti','name' => 'Port-au-Prince','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Port-au-Prince'),
        array('iso' => 'VA','country' => 'Holy See (Vatican City State)','name' => 'Vatican','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Vatican'),
        array('iso' => 'HN','country' => 'Honduras','name' => 'Tegucigalpa','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Tegucigalpa'),
        array('iso' => 'HK','country' => 'Hong Kong','name' => 'Hong Kong','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Hong_Kong'),
        array('iso' => 'HU','country' => 'Hungary','name' => 'Budapest','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Budapest'),
        array('iso' => 'IS','country' => 'Iceland','name' => 'Reykjavik','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Atlantic/Reykjavik'),
        array('iso' => 'IN','country' => 'India','name' => 'Kolkata','gmt_offset' => '5.5','dst_offset' => '5.5','tz' => 'Asia/Kolkata'),
        array('iso' => 'ID','country' => 'Indonesia','name' => 'Jakarta','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Jakarta'),
        array('iso' => 'ID','country' => 'Indonesia','name' => 'Jayapura','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Jayapura'),
        array('iso' => 'ID','country' => 'Indonesia','name' => 'Makassar','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Makassar'),
        array('iso' => 'ID','country' => 'Indonesia','name' => 'Pontianak','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Pontianak'),
        array('iso' => 'IR','country' => 'Iran, Islamic Republic of','name' => 'Tehran','gmt_offset' => '3.5','dst_offset' => '4.5','tz' => 'Asia/Tehran'),
        array('iso' => 'IQ','country' => 'Iraq','name' => 'Baghdad','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Baghdad'),
        array('iso' => 'IE','country' => 'Ireland','name' => 'Dublin','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/Dublin'),
        array('iso' => 'IL','country' => 'Israel','name' => 'Jerusalem','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Asia/Jerusalem'),
        array('iso' => 'IT','country' => 'Italy','name' => 'Rome','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Rome'),
        array('iso' => 'JM','country' => 'Jamaica','name' => 'Jamaica','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Jamaica'),
        array('iso' => 'JP','country' => 'Japan','name' => 'Tokyo','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Tokyo'),
        array('iso' => 'JO','country' => 'Jordan','name' => 'Amman','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Amman'),
        array('iso' => 'KZ','country' => 'Kazakhstan','name' => 'Almaty','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Almaty'),
        array('iso' => 'KZ','country' => 'Kazakhstan','name' => 'Aqtau','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Aqtau'),
        array('iso' => 'KZ','country' => 'Kazakhstan','name' => 'Aqtobe','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Aqtobe'),
        array('iso' => 'KZ','country' => 'Kazakhstan','name' => 'Oral','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Oral'),
        array('iso' => 'KZ','country' => 'Kazakhstan','name' => 'Qyzylorda','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Qyzylorda'),
        array('iso' => 'KE','country' => 'Kenya','name' => 'Nairobi','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Nairobi'),
        array('iso' => 'KI','country' => 'Kiribati','name' => 'Enderbury','gmt_offset' => '13.0','dst_offset' => '13.0','tz' => 'Pacific/Enderbury'),
        array('iso' => 'KI','country' => 'Kiribati','name' => 'Kiritimati','gmt_offset' => '14.0','dst_offset' => '14.0','tz' => 'Pacific/Kiritimati'),
        array('iso' => 'KI','country' => 'Kiribati','name' => 'Tarawa','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Tarawa'),
        array('iso' => 'KP','country' => 'Korea, Democratic People\'s Republic of','name' => 'Pyongyang','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Pyongyang'),
        array('iso' => 'KR','country' => 'Korea, Republic of','name' => 'Seoul','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Seoul'),
        array('iso' => 'KW','country' => 'Kuwait','name' => 'Kuwait','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Kuwait'),
        array('iso' => 'KG','country' => 'Kyrgyzstan','name' => 'Bishkek','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Bishkek'),
        array('iso' => 'LA','country' => 'Lao People\'s Democratic Republic','name' => 'Vientiane','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Vientiane'),
        array('iso' => 'LV','country' => 'Latvia','name' => 'Riga','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Riga'),
        array('iso' => 'LB','country' => 'Lebanon','name' => 'Beirut','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Asia/Beirut'),
        array('iso' => 'LS','country' => 'Lesotho','name' => 'Maseru','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Maseru'),
        array('iso' => 'LR','country' => 'Liberia','name' => 'Monrovia','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Monrovia'),
        array('iso' => 'LY','country' => 'Libyan Arab Jamahiriya','name' => 'Tripoli','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Africa/Tripoli'),
        array('iso' => 'LI','country' => 'Liechtenstein','name' => 'Vaduz','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Vaduz'),
        array('iso' => 'LT','country' => 'Lithuania','name' => 'Vilnius','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Vilnius'),
        array('iso' => 'LU','country' => 'Luxembourg','name' => 'Luxembourg','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Luxembourg'),
        array('iso' => 'MO','country' => 'Macao','name' => 'Macau','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Macau'),
        array('iso' => 'MK','country' => 'Macedonia, the Former Yugoslav Republic of','name' => 'Skopje','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Skopje'),
        array('iso' => 'MG','country' => 'Madagascar','name' => 'Antananarivo','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Indian/Antananarivo'),
        array('iso' => 'MW','country' => 'Malawi','name' => 'Blantyre','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Blantyre'),
        array('iso' => 'MY','country' => 'Malaysia','name' => 'Kuala Lumpur','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Kuala_Lumpur'),
        array('iso' => 'MY','country' => 'Malaysia','name' => 'Kuching','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Kuching'),
        array('iso' => 'MV','country' => 'Maldives','name' => 'Maldives','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Indian/Maldives'),
        array('iso' => 'ML','country' => 'Mali','name' => 'Bamako','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Bamako'),
        array('iso' => 'MT','country' => 'Malta','name' => 'Malta','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Malta'),
        array('iso' => 'MH','country' => 'Marshall Islands','name' => 'Kwajalein','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Kwajalein'),
        array('iso' => 'MH','country' => 'Marshall Islands','name' => 'Majuro','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Majuro'),
        array('iso' => 'MQ','country' => 'Martinique','name' => 'Martinique','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Martinique'),
        array('iso' => 'MR','country' => 'Mauritania','name' => 'Nouakchott','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Nouakchott'),
        array('iso' => 'MU','country' => 'Mauritius','name' => 'Mauritius','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Indian/Mauritius'),
        array('iso' => 'YT','country' => 'Mayotte','name' => 'Mayotte','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Indian/Mayotte'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Bahia Banderas','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Bahia_Banderas'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Cancun','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Cancun'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Chihuahua','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Chihuahua'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Hermosillo','gmt_offset' => '-7.0','dst_offset' => '-7.0','tz' => 'America/Hermosillo'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Matamoros','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Matamoros'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Mazatlan','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Mazatlan'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Merida','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Merida'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Mexico City','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Mexico_City'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Monterrey','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Monterrey'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Ojinaga','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Ojinaga'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Santa Isabel','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Santa_Isabel'),
        array('iso' => 'MX','country' => 'Mexico','name' => 'Tijuana','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Tijuana'),
        array('iso' => 'FM','country' => 'Micronesia, Federated States of','name' => 'Chuuk','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Pacific/Chuuk'),
        array('iso' => 'FM','country' => 'Micronesia, Federated States of','name' => 'Kosrae','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Pacific/Kosrae'),
        array('iso' => 'FM','country' => 'Micronesia, Federated States of','name' => 'Pohnpei','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Pacific/Pohnpei'),
        array('iso' => 'MD','country' => 'Moldova, Republic of','name' => 'Chisinau','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Chisinau'),
        array('iso' => 'MC','country' => 'Monaco','name' => 'Monaco','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Monaco'),
        array('iso' => 'MN','country' => 'Mongolia','name' => 'Choibalsan','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Choibalsan'),
        array('iso' => 'MN','country' => 'Mongolia','name' => 'Hovd','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Hovd'),
        array('iso' => 'MN','country' => 'Mongolia','name' => 'Ulaanbaatar','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Ulaanbaatar'),
        array('iso' => 'MS','country' => 'Montserrat','name' => 'Montserrat','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Montserrat'),
        array('iso' => 'MA','country' => 'Morocco','name' => 'Casablanca','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Africa/Casablanca'),
        array('iso' => 'MZ','country' => 'Mozambique','name' => 'Maputo','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Maputo'),
        array('iso' => 'MM','country' => 'Myanmar','name' => 'Rangoon','gmt_offset' => '6.5','dst_offset' => '6.5','tz' => 'Asia/Rangoon'),
        array('iso' => 'NA','country' => 'Namibia','name' => 'Windhoek','gmt_offset' => '2.0','dst_offset' => '1.0','tz' => 'Africa/Windhoek'),
        array('iso' => 'NR','country' => 'Nauru','name' => 'Nauru','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Nauru'),
        array('iso' => 'NP','country' => 'Nepal','name' => 'Kathmandu','gmt_offset' => '5.8','dst_offset' => '5.8','tz' => 'Asia/Kathmandu'),
        array('iso' => 'NL','country' => 'Netherlands','name' => 'Amsterdam','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Amsterdam'),
        array('iso' => 'NC','country' => 'New Caledonia','name' => 'Noumea','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Pacific/Noumea'),
        array('iso' => 'NZ','country' => 'New Zealand','name' => 'Auckland','gmt_offset' => '13.0','dst_offset' => '12.0','tz' => 'Pacific/Auckland'),
        array('iso' => 'NZ','country' => 'New Zealand','name' => 'Chatham','gmt_offset' => '13.8','dst_offset' => '12.8','tz' => 'Pacific/Chatham'),
        array('iso' => 'NI','country' => 'Nicaragua','name' => 'Managua','gmt_offset' => '-6.0','dst_offset' => '-6.0','tz' => 'America/Managua'),
        array('iso' => 'NE','country' => 'Niger','name' => 'Niamey','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Niamey'),
        array('iso' => 'NG','country' => 'Nigeria','name' => 'Lagos','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Lagos'),
        array('iso' => 'NU','country' => 'Niue','name' => 'Niue','gmt_offset' => '-11.0','dst_offset' => '-11.0','tz' => 'Pacific/Niue'),
        array('iso' => 'NF','country' => 'Norfolk Island','name' => 'Norfolk','gmt_offset' => '11.5','dst_offset' => '11.5','tz' => 'Pacific/Norfolk'),
        array('iso' => 'MP','country' => 'Northern Mariana Islands','name' => 'Saipan','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Pacific/Saipan'),
        array('iso' => 'NO','country' => 'Norway','name' => 'Oslo','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Oslo'),
        array('iso' => 'OM','country' => 'Oman','name' => 'Muscat','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Asia/Muscat'),
        array('iso' => 'PK','country' => 'Pakistan','name' => 'Karachi','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Karachi'),
        array('iso' => 'PW','country' => 'Palau','name' => 'Palau','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Pacific/Palau'),
        array('iso' => 'PS','country' => 'Palestinian Territory, Occupied','name' => 'Gaza','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Asia/Gaza'),
        array('iso' => 'PS','country' => 'Palestinian Territory, Occupied','name' => 'Hebron','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Asia/Hebron'),
        array('iso' => 'PA','country' => 'Panama','name' => 'Panama','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Panama'),
        array('iso' => 'PG','country' => 'Papua New Guinea','name' => 'Port Moresby','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Pacific/Port_Moresby'),
        array('iso' => 'PY','country' => 'Paraguay','name' => 'Asuncion','gmt_offset' => '-3.0','dst_offset' => '-4.0','tz' => 'America/Asuncion'),
        array('iso' => 'PE','country' => 'Peru','name' => 'Lima','gmt_offset' => '-5.0','dst_offset' => '-5.0','tz' => 'America/Lima'),
        array('iso' => 'PH','country' => 'Philippines','name' => 'Manila','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Manila'),
        array('iso' => 'PN','country' => 'Pitcairn','name' => 'Pitcairn','gmt_offset' => '-8.0','dst_offset' => '-8.0','tz' => 'Pacific/Pitcairn'),
        array('iso' => 'PL','country' => 'Poland','name' => 'Warsaw','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Warsaw'),
        array('iso' => 'PT','country' => 'Portugal','name' => 'Azores','gmt_offset' => '-1.0','dst_offset' => '0.0','tz' => 'Atlantic/Azores'),
        array('iso' => 'PT','country' => 'Portugal','name' => 'Madeira','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Atlantic/Madeira'),
        array('iso' => 'PT','country' => 'Portugal','name' => 'Lisbon','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/Lisbon'),
        array('iso' => 'PR','country' => 'Puerto Rico','name' => 'Puerto Rico','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Puerto_Rico'),
        array('iso' => 'QA','country' => 'Qatar','name' => 'Qatar','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Qatar'),
        array('iso' => 'RE','country' => 'Reunion','name' => 'Reunion','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Indian/Reunion'),
        array('iso' => 'RO','country' => 'Romania','name' => 'Bucharest','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Bucharest'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Anadyr','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Asia/Anadyr'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Irkutsk','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Irkutsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Kamchatka','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Asia/Kamchatka'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Krasnoyarsk','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Krasnoyarsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Magadan','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Asia/Magadan'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Novokuznetsk','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Novokuznetsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Novosibirsk','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Novosibirsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Omsk','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Omsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Sakhalin','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Asia/Sakhalin'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Vladivostok','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Asia/Vladivostok'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Yakutsk','gmt_offset' => '10.0','dst_offset' => '10.0','tz' => 'Asia/Yakutsk'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Yekaterinburg','gmt_offset' => '6.0','dst_offset' => '6.0','tz' => 'Asia/Yekaterinburg'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Kaliningrad','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Europe/Kaliningrad'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Moscow','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Europe/Moscow'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Samara','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Europe/Samara'),
        array('iso' => 'RU','country' => 'Russian Federation','name' => 'Volgograd','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Europe/Volgograd'),
        array('iso' => 'RW','country' => 'Rwanda','name' => 'Kigali','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Kigali'),
        array('iso' => 'SH','country' => 'Saint Helena','name' => 'St Helena','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Atlantic/St_Helena'),
        array('iso' => 'KN','country' => 'Saint Kitts and Nevis','name' => 'St Kitts','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/St_Kitts'),
        array('iso' => 'LC','country' => 'Saint Lucia','name' => 'St Lucia','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/St_Lucia'),
        array('iso' => 'PM','country' => 'Saint Pierre and Miquelon','name' => 'Miquelon','gmt_offset' => '-3.0','dst_offset' => '-2.0','tz' => 'America/Miquelon'),
        array('iso' => 'VC','country' => 'Saint Vincent and the Grenadines','name' => 'St Vincent','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/St_Vincent'),
        array('iso' => 'WS','country' => 'Samoa','name' => 'Apia','gmt_offset' => '14.0','dst_offset' => '13.0','tz' => 'Pacific/Apia'),
        array('iso' => 'SM','country' => 'San Marino','name' => 'San Marino','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/San_Marino'),
        array('iso' => 'ST','country' => 'Sao Tome and Principe','name' => 'Sao Tome','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Sao_Tome'),
        array('iso' => 'SA','country' => 'Saudi Arabia','name' => 'Riyadh','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Riyadh'),
        array('iso' => 'SN','country' => 'Senegal','name' => 'Dakar','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Dakar'),
        array('iso' => 'SC','country' => 'Seychelles','name' => 'Mahe','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Indian/Mahe'),
        array('iso' => 'SL','country' => 'Sierra Leone','name' => 'Freetown','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Freetown'),
        array('iso' => 'SG','country' => 'Singapore','name' => 'Singapore','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Singapore'),
        array('iso' => 'SK','country' => 'Slovakia','name' => 'Bratislava','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Bratislava'),
        array('iso' => 'SI','country' => 'Slovenia','name' => 'Ljubljana','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Ljubljana'),
        array('iso' => 'SB','country' => 'Solomon Islands','name' => 'Guadalcanal','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Pacific/Guadalcanal'),
        array('iso' => 'SO','country' => 'Somalia','name' => 'Mogadishu','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Mogadishu'),
        array('iso' => 'ZA','country' => 'South Africa','name' => 'Johannesburg','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Johannesburg'),
        array('iso' => 'GS','country' => 'South Georgia and the South Sandwich Islands','name' => 'South Georgia','gmt_offset' => '-2.0','dst_offset' => '-2.0','tz' => 'Atlantic/South_Georgia'),
        array('iso' => 'ES','country' => 'Spain','name' => 'Ceuta','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Africa/Ceuta'),
        array('iso' => 'ES','country' => 'Spain','name' => 'Canary','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Atlantic/Canary'),
        array('iso' => 'ES','country' => 'Spain','name' => 'Madrid','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Madrid'),
        array('iso' => 'LK','country' => 'Sri Lanka','name' => 'Colombo','gmt_offset' => '5.5','dst_offset' => '5.5','tz' => 'Asia/Colombo'),
        array('iso' => 'SD','country' => 'Sudan','name' => 'Khartoum','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Khartoum'),
        array('iso' => 'SR','country' => 'Suriname','name' => 'Paramaribo','gmt_offset' => '-3.0','dst_offset' => '-3.0','tz' => 'America/Paramaribo'),
        array('iso' => 'SJ','country' => 'Svalbard and Jan Mayen','name' => 'Longyearbyen','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Arctic/Longyearbyen'),
        array('iso' => 'SZ','country' => 'Swaziland','name' => 'Mbabane','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Mbabane'),
        array('iso' => 'SE','country' => 'Sweden','name' => 'Stockholm','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Stockholm'),
        array('iso' => 'CH','country' => 'Switzerland','name' => 'Zurich','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Zurich'),
        array('iso' => 'SY','country' => 'Syrian Arab Republic','name' => 'Damascus','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Asia/Damascus'),
        array('iso' => 'TW','country' => 'Taiwan, Province of China','name' => 'Taipei','gmt_offset' => '8.0','dst_offset' => '8.0','tz' => 'Asia/Taipei'),
        array('iso' => 'TJ','country' => 'Tajikistan','name' => 'Dushanbe','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Dushanbe'),
        array('iso' => 'TZ','country' => 'Tanzania, United Republic of','name' => 'Dar es Salaam','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Dar_es_Salaam'),
        array('iso' => 'TH','country' => 'Thailand','name' => 'Bangkok','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Bangkok'),
        array('iso' => 'TL','country' => 'Timor-Leste','name' => 'Dili','gmt_offset' => '9.0','dst_offset' => '9.0','tz' => 'Asia/Dili'),
        array('iso' => 'TG','country' => 'Togo','name' => 'Lome','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/Lome'),
        array('iso' => 'TK','country' => 'Tokelau','name' => 'Fakaofo','gmt_offset' => '13.0','dst_offset' => '13.0','tz' => 'Pacific/Fakaofo'),
        array('iso' => 'TO','country' => 'Tonga','name' => 'Tongatapu','gmt_offset' => '13.0','dst_offset' => '13.0','tz' => 'Pacific/Tongatapu'),
        array('iso' => 'TT','country' => 'Trinidad and Tobago','name' => 'Port of Spain','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Port_of_Spain'),
        array('iso' => 'TN','country' => 'Tunisia','name' => 'Tunis','gmt_offset' => '1.0','dst_offset' => '1.0','tz' => 'Africa/Tunis'),
        array('iso' => 'TR','country' => 'Turkey','name' => 'Istanbul','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Istanbul'),
        array('iso' => 'TM','country' => 'Turkmenistan','name' => 'Ashgabat','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Ashgabat'),
        array('iso' => 'TC','country' => 'Turks and Caicos Islands','name' => 'Grand Turk','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Grand_Turk'),
        array('iso' => 'TV','country' => 'Tuvalu','name' => 'Funafuti','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Funafuti'),
        array('iso' => 'UG','country' => 'Uganda','name' => 'Kampala','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Kampala'),
        array('iso' => 'UA','country' => 'Ukraine','name' => 'Kiev','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Kiev'),
        array('iso' => 'UA','country' => 'Ukraine','name' => 'Simferopol','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Simferopol'),
        array('iso' => 'UA','country' => 'Ukraine','name' => 'Uzhgorod','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Uzhgorod'),
        array('iso' => 'UA','country' => 'Ukraine','name' => 'Zaporozhye','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Zaporozhye'),
        array('iso' => 'AE','country' => 'United Arab Emirates','name' => 'Dubai','gmt_offset' => '4.0','dst_offset' => '4.0','tz' => 'Asia/Dubai'),
        array('iso' => 'GB','country' => 'United Kingdom','name' => 'London','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/London'),
        array('iso' => 'US','country' => 'United States','name' => 'Adak','gmt_offset' => '-10.0','dst_offset' => '-9.0','tz' => 'America/Adak'),
        array('iso' => 'US','country' => 'United States','name' => 'Anchorage','gmt_offset' => '-9.0','dst_offset' => '-8.0','tz' => 'America/Anchorage'),
        array('iso' => 'US','country' => 'United States','name' => 'Boise','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Boise'),
        array('iso' => 'US','country' => 'United States','name' => 'Chicago','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Chicago'),
        array('iso' => 'US','country' => 'United States','name' => 'Denver','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Denver'),
        array('iso' => 'US','country' => 'United States','name' => 'Detroit','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Detroit'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Indianapolis','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Indianapolis'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Knox','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Indiana/Knox'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Marengo','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Marengo'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Petersburg','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Petersburg'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Tell City','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Indiana/Tell_City'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Vevay','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Vevay'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Vincennes','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Vincennes'),
        array('iso' => 'US','country' => 'United States','name' => 'Indiana/Winamac','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Indiana/Winamac'),
        array('iso' => 'US','country' => 'United States','name' => 'Juneau','gmt_offset' => '-9.0','dst_offset' => '-8.0','tz' => 'America/Juneau'),
        array('iso' => 'US','country' => 'United States','name' => 'Kentucky/Louisville','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Kentucky/Louisville'),
        array('iso' => 'US','country' => 'United States','name' => 'Kentucky/Monticello','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/Kentucky/Monticello'),
        array('iso' => 'US','country' => 'United States','name' => 'Los Angeles','gmt_offset' => '-8.0','dst_offset' => '-7.0','tz' => 'America/Los_Angeles'),
        array('iso' => 'US','country' => 'United States','name' => 'Menominee','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/Menominee'),
        array('iso' => 'US','country' => 'United States','name' => 'Metlakatla','gmt_offset' => '-8.0','dst_offset' => '-8.0','tz' => 'America/Metlakatla'),
        array('iso' => 'US','country' => 'United States','name' => 'New York','gmt_offset' => '-5.0','dst_offset' => '-4.0','tz' => 'America/New_York'),
        array('iso' => 'US','country' => 'United States','name' => 'Nome','gmt_offset' => '-9.0','dst_offset' => '-8.0','tz' => 'America/Nome'),
        array('iso' => 'US','country' => 'United States','name' => 'North Dakota/Beulah','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/North_Dakota/Beulah'),
        array('iso' => 'US','country' => 'United States','name' => 'North Dakota/Center','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/North_Dakota/Center'),
        array('iso' => 'US','country' => 'United States','name' => 'North Dakota/New Salem','gmt_offset' => '-6.0','dst_offset' => '-5.0','tz' => 'America/North_Dakota/New_Salem'),
        array('iso' => 'US','country' => 'United States','name' => 'Phoenix','gmt_offset' => '-7.0','dst_offset' => '-7.0','tz' => 'America/Phoenix'),
        array('iso' => 'US','country' => 'United States','name' => 'Shiprock','gmt_offset' => '-7.0','dst_offset' => '-6.0','tz' => 'America/Shiprock'),
        array('iso' => 'US','country' => 'United States','name' => 'Sitka','gmt_offset' => '-9.0','dst_offset' => '-8.0','tz' => 'America/Sitka'),
        array('iso' => 'US','country' => 'United States','name' => 'Yakutat','gmt_offset' => '-9.0','dst_offset' => '-8.0','tz' => 'America/Yakutat'),
        array('iso' => 'US','country' => 'United States','name' => 'Honolulu','gmt_offset' => '-10.0','dst_offset' => '-10.0','tz' => 'Pacific/Honolulu'),
        array('iso' => 'UM','country' => 'United States Minor Outlying Islands','name' => 'Johnston','gmt_offset' => '-10.0','dst_offset' => '-10.0','tz' => 'Pacific/Johnston'),
        array('iso' => 'UM','country' => 'United States Minor Outlying Islands','name' => 'Midway','gmt_offset' => '-11.0','dst_offset' => '-11.0','tz' => 'Pacific/Midway'),
        array('iso' => 'UM','country' => 'United States Minor Outlying Islands','name' => 'Wake','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Wake'),
        array('iso' => 'UY','country' => 'Uruguay','name' => 'Montevideo','gmt_offset' => '-2.0','dst_offset' => '-3.0','tz' => 'America/Montevideo'),
        array('iso' => 'UZ','country' => 'Uzbekistan','name' => 'Samarkand','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Samarkand'),
        array('iso' => 'UZ','country' => 'Uzbekistan','name' => 'Tashkent','gmt_offset' => '5.0','dst_offset' => '5.0','tz' => 'Asia/Tashkent'),
        array('iso' => 'VU','country' => 'Vanuatu','name' => 'Efate','gmt_offset' => '11.0','dst_offset' => '11.0','tz' => 'Pacific/Efate'),
        array('iso' => 'VE','country' => 'Venezuela','name' => 'Caracas','gmt_offset' => '-4.5','dst_offset' => '-4.5','tz' => 'America/Caracas'),
        array('iso' => 'VN','country' => 'Viet Nam','name' => 'Ho Chi Minh','gmt_offset' => '7.0','dst_offset' => '7.0','tz' => 'Asia/Ho_Chi_Minh'),
        array('iso' => 'VG','country' => 'Virgin Islands, British','name' => 'Tortola','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Tortola'),
        array('iso' => 'VI','country' => 'Virgin Islands, U.s.','name' => 'St Thomas','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/St_Thomas'),
        array('iso' => 'WF','country' => 'Wallis and Futuna','name' => 'Wallis','gmt_offset' => '12.0','dst_offset' => '12.0','tz' => 'Pacific/Wallis'),
        array('iso' => 'EH','country' => 'Western Sahara','name' => 'El Aaiun','gmt_offset' => '0.0','dst_offset' => '0.0','tz' => 'Africa/El_Aaiun'),
        array('iso' => 'YE','country' => 'Yemen','name' => 'Aden','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Asia/Aden'),
        array('iso' => 'ZM','country' => 'Zambia','name' => 'Lusaka','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Lusaka'),
        array('iso' => 'ZW','country' => 'Zimbabwe','name' => 'Harare','gmt_offset' => '2.0','dst_offset' => '2.0','tz' => 'Africa/Harare'),
        array('iso' => 'AX','country' => 'Aland Islands','name' => 'Mariehamn','gmt_offset' => '2.0','dst_offset' => '3.0','tz' => 'Europe/Mariehamn'),
        array('iso' => 'BL','country' => 'Saint Barthelemy','name' => 'St Barthelemy','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/St_Barthelemy'),
        array('iso' => 'BQ','country' => 'Bonaire, Saint Eustatius and Saba ','name' => 'Kralendijk','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Kralendijk'),
        array('iso' => 'CW','country' => 'Curacao','name' => 'Curacao','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Curacao'),
        array('iso' => 'GG','country' => 'Guernsey','name' => 'Guernsey','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/Guernsey'),
        array('iso' => 'IM','country' => 'Isle of Man','name' => 'Isle of Man','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/Isle_of_Man'),
        array('iso' => 'JE','country' => 'Jersey','name' => 'Jersey','gmt_offset' => '0.0','dst_offset' => '1.0','tz' => 'Europe/Jersey'),
        array('iso' => 'ME','country' => 'Montenegro','name' => 'Podgorica','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Podgorica'),
        array('iso' => 'MF','country' => 'Saint Martin','name' => 'Marigot','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Marigot'),
        array('iso' => 'RS','country' => 'Serbia','name' => 'Belgrade','gmt_offset' => '1.0','dst_offset' => '2.0','tz' => 'Europe/Belgrade'),
        array('iso' => 'SS','country' => 'South Sudan','name' => 'Juba','gmt_offset' => '3.0','dst_offset' => '3.0','tz' => 'Africa/Juba'),
        array('iso' => 'SX','country' => 'Sint Maarten','name' => 'Lower Princes','gmt_offset' => '-4.0','dst_offset' => '-4.0','tz' => 'America/Lower_Princes')
    )
);
